services:
  - type: web
    name: django-backend
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn abiatechcommBE.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
